---
title: "Further reading"
author:
  - name: "Ellis Franklin"
date: "2025-02-06"
date-format: long
number-sections: true
number-depth: 3
toc: true
from: markdown+emoji
format: html
bibliography: references.bib
---

<br/> 

## Some resources for learning more about Quarto

-   Casajus N, Bonnici I, Dray S, Gimenez O, Guéry L, Guilhaumon F, Schiettekatte NMD & Siberchicot A (2024) FRB-CESAB & GdR EcoStat training course: Reproducible Research in Computational Ecology. Zenodo. URL: <http://doi.org/10.5281/zenodo.4262978> ([link to workshop](https://rdatatoolbox.github.io/chapters/ex-compendium.html))

-   "*Introduction to Quarto*" by Andrew Bray at posit::conf(2024) ([link](https://posit-conf-2024.github.io/quarto-intro/))

-   "*With Quarto Coming, is R Markdwon Going Away? No*" blog post by Yihui Xie ([link](https://yihui.org/en/2022/04/quarto-r-markdown/))

-   "*Introduction to Quarto*" by Eric Delmelle ([link](https://ericdelmelle.github.io/introToQuarto/#/title-slide))

<br/>


## Some resources for understanding Reproducible Research 

-   Casajus N, Bonnici I, Dray S, Gimenez O, Guéry L, Guilhaumon F, Schiettekatte NMD & Siberchicot A (2024) FRB-CESAB & GdR EcoStat training course: Reproducible Research in Computational Ecology. Zenodo. (<http://doi.org/10.5281/zenodo.4262978>) ([link to workshop](https://rdatatoolbox.github.io/chapters/ex-compendium.html))

-   Repro4Everyone. (n.d.). *Introduction to Reproducibility*. Repro4Everyone. ([link](https://www.repro4everyone.org/resources/intro-reproducibility))

-   "*Guide for Reproducible Research*" by The Turing Way Community. DOI: [10.5281/zenodo.3332807](https://doi.org/10.5281/zenodo.3332807) ([link to the guide](https://book.the-turing-way.org/reproducible-research/reproducible-research.html))

-   "*A conside guide to reproducible research using secondary data*" by Katharina Blankart, Maryna Ivets, Eva Goetjes and Kai Miele ([link](https://katblankart.github.io/DataLiteracy/intro.html))

<br/>

## Literature on Reproducible Research

-   @claerbout1992
-   @loscalzo2012
-   @freedman2015a
-   @baker2016
-   @this2017
-   @plesser2018
-   @marwick2018
-   @plesser2018
-   @schloss2018b
-   @reproduc2019
-   @desquilbet2019a
-   @gundersen2021a
-   @alston2021
-   @ziemann2023
-   @calnan2024
-   @casajus2024
-   @reproduc
-   @sixfact
